{% macro statcast_template(year) %}

with source as (

    select * from {{ source('statcast', 'statcast_{{ year }}') }}

),

renamed as (

    select
        cast(r.index as int64) as index,
        cast(r.game_pk as int64) as game_id,
        cast(r.game_date as date) as game_date,
        cast(r.game_year as int64) as game_year,
        -- E = EX, S = ST, R = RS, F = WC, D = DS, L = LC, W = WS
        cast(r.game_type as string) as game_type,
        cast(r.home_team as string) as home_team,
        cast(r.away_team as string) as away_team,
        cast(r.home_score as int64) as home_score,
        cast(r.away_score as int64) as away_score,
        cast(r.post_home_score as int64) as post_home_score,
        cast(r.post_away_score as int64) as post_away_score,
        cast(r.bat_score as int64) as batting_team_score,
        cast(r.fld_score as int64) as fielding_team_score,
        cast(r.batter as int64) as batter_mlb_id,
        cast(r.pitcher as int64) as pitcher_mlb_id,
        cast(r.fielder_2 as int64) as catcher_mlb_id,
        cast(r.fielder_3 as int64) as first_base_mlb_id,
        cast(r.fielder_4 as int64) as second_base_mlb_id,
        cast(r.fielder_5 as int64) as third_base_mlb_id,
        cast(r.fielder_6 as int64) as shortstop_mlb_id,
        cast(r.fielder_7 as int64) as left_field_mlb_id,
        cast(r.fielder_8 as int64) as center_field_mlb_id,
        cast(r.fielder_9 as int64) as right_field_mlb_id,
        cast(r.stand as string) as batter_stand,
        cast(r.p_throws as string) as pitcher_hand,
        cast(r.inning as int64) as inning,
        cast(r.inning_topbot as int64) as half_inning,
        cast(r.at_bat_number as int64) as game_plate_appearance,
        cast(r.pitch_number as int64) as pitch_number,
        cast(r.balls as int64) as balls,
        cast(r.strikes as int64) as strikes,
        cast(r.outs_when_up as int64) as outs,
        cast(r.if_fielding_alignment as string) as infield_alignment,
        cast(r.of_fielding_alignment as string) as outfield_alignment,
        cast(r.on_1b as int64) as runner_on_first_mlb_id,
        cast(r.on_2b as int64) as runner_on_second_mlb_id,
        cast(r.on_3b as int64) as runner_on_third_mlb_id,
        parse_datetime('%y%m%d_%H%M%S', r.sv_id) as pitched_at,
        cast(r.pitch_type as string) as pitch_type,
        cast(r.pitch_name as string) as pitch_name,
        cast(r.sz_top as numeric) as strike_zone_top,
        cast(r.sz_bot as numeric) as strike_zone_bottom,
        cast(r.release_speed as numeric) as release_speed,
        cast(r.release_spin_rate as int64) as release_spin_rate,
        cast(r.release_extension as numeric) as release_extension,
        cast(r.release_pos_x as numeric) as release_position_x,
        cast(r.release_pos_y as numeric) as release_position_y,
        cast(r.release_pos_z as numeric) as release_position_z,
        cast(r.vx0 as numeric) as velocity_50_x,
        cast(r.vy0 as numeric) as velocity_50_y,
        cast(r.vz0 as numeric) as velocity_50_z,
        cast(r.ax0 as numeric) as acceleration_50_x,
        cast(r.ay0 as numeric) as acceleration_50_y,
        cast(r.az0 as numeric) as acceleration_50_z,
        cast(r.pfx_x as numeric) as movement_x,
        cast(r.pfx_z as numeric) as movement_z,
        cast(r.plate_x as numeric) as plate_x,
        cast(r.plate_z as numeric) as plate_z,
        cast(r.zone as zone) as strike_zone_location,
        cast(r.effective_speed as numeric) as effective_speed,
        cast(r.events as string) as plate_appearance_result,
        cast(r.des as string) as plate_appearance_result_description,
        cast(r.type as string) as pitch_result,
        cast(r.description as string) as pitch_result_description,
        cast(r.bb_type as string) as batted_ball_type,
        cast(r.hit_location as int64) as initial_fielder,
        cast(r.hc_x as numeric) as hit_coordinate_x,
        cast(r.hc_y as numeric) as hit_coordinate_y,
        cast(r.hit_distance_sc as numeric) as hit_distance,
        cast(r.launch_speed as numeric) as exit_velocity,
        cast(r.launch_angle as int64) as launch_angle,
        cast(r.launch_speed_angle as int64) as launch_speed_angle,
        cast(r.estimated_ba_using_speedangle as numeric) as estimated_batting_average,
        cast(r.estiamted_woba_using_speedangle as numeric) as estimated_woba,
        cast(r.woba_value as numeric) as woba_value,
        cast(r.woba_denom as numeric) as woba_denominator,
        cast(r.babip_value as int64) as babip_value,
        cast(r.iso_value as int64) as number_of_extra_bases

    from source as s
)

{% endmacro %}
